site_name: react-jsonschema-form documentation
docs_dir: docs
theme: readthedocs

extra_javascript: [main.js]

nav:
  - Introduction: index.md
  - Quickstart: quickstart.md
  - Usage:
    - JSON Schema: usage/schema.md
    - uiSchema: usage/uiSchema.md
    - Widgets: usage/widgets.md
    - Themes: usage/themes.md
    - Validation: usage/validation.md
  - Advanced Customization:
    - Custom Widgets and Fields: advanced-customization/custom-widgets-fields.md
    - Custom Templates: advanced-customization/custom-templates.md
    - Custom Themes: advanced-customization/custom-themes.md
    - Other Internals: advanced-customization/internals.md
    - Contributing: contributing.md
  - API Reference:
    - "&lt;Form /&gt; props": api-reference/form-props.md

markdown_extensions:
  - toc:
      permalink: true
