site_name: react-jsonschema-form documentation
docs_dir: docs
theme: readthedocs

markdown_extensions:
  - markdown_include.include:
      base_path: docs

nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Usage:
    - Using JSON Schema: usage/schema.md
    - Using uiSchema: usage/uiSchema.md
    - Using widgets: usage/widgets.md
    - Using themes: usage/themes.md
    - "&lt;Form /&gt; props": usage/form-props.md
  - Advanced Customization:
    - Custom Widgets and Fields: advanced-customization/custom-widgets-fields.md
    - Custom Templates: advanced-customization/custom-templates.md
    - Custom Themes: advanced-customization/custom-themes.md
    - Other Internals: advanced-customization/internals.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
